import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";
import { TimerProvider } from "@/Provider/TimerProvider";
import { AuthProvider } from "@/Provider/AuthProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Memoria",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
            >
                <AuthProvider>
                    <TimerProvider>
                        <NavBar />
                        <main className="flex-1 w-full bg-neutral-950 flex flex-col justify-center items-center h-screen">
                            {children}
                        </main>
                    </TimerProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
